title:  DSC LIU - Yemen
author: # Is the DSC Chapter
  name:  DSC - Lebanese International University
  email: gdscliu@gmail.com
  location: Sanaa - Yemen
  phone:
description: The offical website for the Lebanese International University Developer Student Club.
current_term: "2021" # should be the last 2 digits of the years ex. 2020-2021 > "2021" ; 2021-2022 > "2122"
site_logo: assets/dscliu-logo.png
maintainer: 'Site Maintained by <a href="https://www.mutahar.me/">Khaldoon Mutahar</a>'
timezone: Etc/GMT

url: "https://www.gdscliu.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

show_excerpts: false # set to true to show excerpts on the homepage

# Navigation bar links
navbar-links:
  Home: "/"
  Our Team: "2021/team/"
  About DSC: "https://developers.google.com/community/gdsc"
  Join Us: "https://gdsc.community.dev/lebanese-international-university-sanaa/"

# jekyll-them-dscliu date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-dscliu:
  date_format: "%b %-d, %Y"

# Use the Username not the full URL path
social_links:
  twitter: gdscliu
  github: gdscliu
  facebook: gdscliu
  instagram: gdscliu
  youtube: UCs4JhdOCxlMfhI7VMhWmEHw
  youtube_channel:
  youtube_channel_name:
  telegram:
  devto:
  dribbble:
  flickr:
  linkedin:
  pinterest:

analytics: # Only use one and leave the rest blank (Advanced Users: using more than one will require edits to the _includes section)
  gtm: GTM-5BB8294
  ga:

# Build settings
theme: jekyll-theme-dscliu

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - README.md

include:
  - _pages
  - _redirects
